version: '3.8'

services:
  node:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./web:/app
      - /app/node_modules

  firebase_emulator:
    build:
      context: ./firebase
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
      - 4400:4400
      - 4500:4500
      - 5001:5001
      - 8085:8085
      - 9099:9099
      - 9199:9199
    volumes:
      - ./firebase:/app
    command: firebase emulators:start --project demo-app

